### ISSUE TITLE
Common Error: Problem building

### ISSUE THREAD

**Issue by minakhan01** [minakhan01/Mathland2.0#8]
- open project settings by clicking on the exclamation mark (triangle) and the unity project
<img width="273" alt="screen shot 2018-02-26 at 9 19 49 am" src="https://user-images.githubusercontent.com/6627535/36675420-debd1aa0-1ad6-11e8-9eb5-07d79657a73a.png">

- change the bundle identifier and team
<img width="670" alt="screen shot 2018-02-26 at 9 20 07 am" src="https://user-images.githubusercontent.com/6627535/36675399-cd6db14c-1ad6-11e8-98ca-a1abf8a5f51c.png">

- change the Wikitude thing to Option from Required
<img width="651" alt="screen shot 2018-02-26 at 9 20 19 am" src="https://user-images.githubusercontent.com/6627535/36675324-a16c3370-1ad6-11e8-907e-2bb6ea037f24.png">

**Comment by judsirera** [comment]
When I try to install on my phone, this error pops-up. Is something related to MIRA
![screen shot 2018-02-26 at 10 18 24 am](https://user-images.githubusercontent.com/16387484/36678356-83e52db8-1ade-11e8-8dab-278875d5f27a.png)

**Comment by judsirera** [comment]
I solved changing the version to **9.0**
